[workspace]

[package]
name = "rusteron-replay-reproduction"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rusteron-archive = "0.1"
rusteron-client = "0.1"

[[bin]]
name = "external_replay"

[[bin]]
name = "embedded_replay"